-- Migration script to handle existing NULL values in new columns
-- This script helps ensure consistent audit trail behavior

-- Option 1: Set default values for existing NULL records (adjust default values as needed)
/*
UPDATE TCIL_MST_HOLIDAY_OFFERS 
SET 
    IMAGE_NAME = COALESCE(IMAGE_NAME, ''),
    IMAGE_ALT_TAG = COALESCE(IMAGE_ALT_TAG, ''),
    HOLIDAY_TYPE = COALESCE(HOLIDAY_TYPE, ''),
    INTERNAL_OFFER = COALESCE(INTERNAL_OFFER, ''),
    MODULE = COALESCE(MODULE, ''),
    PROMO_CODE_NAME = COALESCE(PROMO_CODE_NAME, ''),
    DESTINATION_NAME = COALESCE(DESTINATION_NAME, ''),
    REMARK = COALESCE(REMARK, '')
WHERE 
    IMAGE_NAME IS NULL OR 
    IMAGE_ALT_TAG IS NULL OR 
    HOLIDAY_TYPE IS NULL OR 
    INTERNAL_OFFER IS NULL OR 
    MODULE IS NULL OR 
    PROMO_CODE_NAME IS NULL OR 
    DESTINATION_NAME IS NULL OR 
    REMARK IS NULL;
*/

-- Option 2: Add audit entries for existing records that were updated before the trigger fix
/*
INSERT INTO TCIL_MST_HOLIDAY_OFFERS_AUDIT (
    HOLIDAY_OFFER_ID,
    UPDATE_DATE,
    UPDATED_BY,
    IP,
    HISTORY
)
SELECT 
    HOLIDAY_OFFER_ID,
    NOW(),
    'SYSTEM_MIGRATION',
    '127.0.0.1',
    'Migration audit entry for existing record with new columns'
FROM TCIL_MST_HOLIDAY_OFFERS 
WHERE HOLIDAY_OFFER_ID NOT IN (
    SELECT DISTINCT HOLIDAY_OFFER_ID 
    FROM TCIL_MST_HOLIDAY_OFFERS_AUDIT
);
*/

-- Option 3: Check for records that might need attention
SELECT 
    HOLIDAY_OFFER_ID,
    HOLIDAY_OFFER_NAME,
    CASE WHEN IMAGE_NAME IS NULL THEN 'NULL' ELSE 'HAS_VALUE' END AS IMAGE_NAME_STATUS,
    CASE WHEN IMAGE_ALT_TAG IS NULL THEN 'NULL' ELSE 'HAS_VALUE' END AS IMAGE_ALT_TAG_STATUS,
    CASE WHEN HOLIDAY_TYPE IS NULL THEN 'NULL' ELSE 'HAS_VALUE' END AS HOLIDAY_TYPE_STATUS,
    CASE WHEN INTERNAL_OFFER IS NULL THEN 'NULL' ELSE 'HAS_VALUE' END AS INTERNAL_OFFER_STATUS,
    CASE WHEN MODULE IS NULL THEN 'NULL' ELSE 'HAS_VALUE' END AS MODULE_STATUS,
    CASE WHEN PROMO_CODE_NAME IS NULL THEN 'NULL' ELSE 'HAS_VALUE' END AS PROMO_CODE_NAME_STATUS,
    CASE WHEN DESTINATION_NAME IS NULL THEN 'NULL' ELSE 'HAS_VALUE' END AS DESTINATION_NAME_STATUS,
    CASE WHEN REMARK IS NULL THEN 'NULL' ELSE 'HAS_VALUE' END AS REMARK_STATUS
FROM TCIL_MST_HOLIDAY_OFFERS
WHERE 
    IMAGE_NAME IS NULL OR 
    IMAGE_ALT_TAG IS NULL OR 
    HOLIDAY_TYPE IS NULL OR 
    INTERNAL_OFFER IS NULL OR 
    MODULE IS NULL OR 
    PROMO_CODE_NAME IS NULL OR 
    DESTINATION_NAME IS NULL OR 
    REMARK IS NULL
ORDER BY HOLIDAY_OFFER_ID;