-- Drop existing triggers first
DROP TRIGGER IF EXISTS `TCIL_MST_HOLIDAY_OFFERS_AFTER_INSERT`;
DROP TRIGGER IF EXISTS `UPDATE_TCIL_MST_HOLIDAY_OFFERS`;

-- Recreate INSERT trigger with consistent definer
DELIMITER $$

CREATE TRIGGER `TCIL_MST_HOLIDAY_OFFERS_AFTER_INSERT` 
AFTER INSERT ON `TCIL_MST_HOLIDAY_OFFERS` 
FOR EACH ROW 
BEGIN
   INSERT INTO TCIL_MST_HOLIDAY_OFFERS_AUDIT
    SET HOLIDAY_OFFER_ID = NEW.HOLIDAY_OFFER_ID,
        UPDATE_DATE = NOW(),
        UPDATED_BY = NEW.CREATED_BY,
        IP = NEW.IP,
        HISTORY = 'NEW HOLIDAY OFFER HAS BEEN CREATED';
END$$

-- Recreate UPDATE trigger with proper NULL handling
CREATE TRIGGER `UPDATE_TCIL_MST_HOLIDAY_OFFERS` 
AFTER UPDATE ON `TCIL_MST_HOLIDAY_OFFERS` 
FOR EACH ROW 
BEGIN
    DECLARE UPDATE_HISTORY LONGTEXT;
    SET UPDATE_HISTORY := '';

    -- Handle HOLIDAY_OFFER_NAME with NULL check
    IF (COALESCE(NEW.HOLIDAY_OFFER_NAME, '') != COALESCE(OLD.HOLIDAY_OFFER_NAME, '')) THEN
        SET UPDATE_HISTORY := CONCAT(UPDATE_HISTORY, '-> OLD NAME: ', COALESCE(OLD.HOLIDAY_OFFER_NAME, 'NULL'), 
                                     '; NEW NAME: ', COALESCE(NEW.HOLIDAY_OFFER_NAME, 'NULL'), CHAR(13), CHAR(10));
    END IF;

    -- Handle IS_ACTIVE with NULL check
    IF (COALESCE(NEW.IS_ACTIVE, '') != COALESCE(OLD.IS_ACTIVE, '')) THEN
        SET UPDATE_HISTORY := CONCAT(UPDATE_HISTORY, '-> OLD IS_ACTIVE: ', COALESCE(OLD.IS_ACTIVE, 'NULL'), 
                                     '; NEW IS_ACTIVE: ', COALESCE(NEW.IS_ACTIVE, 'NULL'), CHAR(13), CHAR(10));
    END IF;

    -- Handle IMAGE_NAME with NULL check
    IF (COALESCE(NEW.IMAGE_NAME, '') != COALESCE(OLD.IMAGE_NAME, '')) THEN
        SET UPDATE_HISTORY := CONCAT(UPDATE_HISTORY, '-> OLD IMAGE_NAME: ', COALESCE(OLD.IMAGE_NAME, 'NULL'), 
                                     '; NEW IMAGE_NAME: ', COALESCE(NEW.IMAGE_NAME, 'NULL'), CHAR(13), CHAR(10));
    END IF;

    -- Handle IMAGE_ALT_TAG with NULL check
    IF (COALESCE(NEW.IMAGE_ALT_TAG, '') != COALESCE(OLD.IMAGE_ALT_TAG, '')) THEN
        SET UPDATE_HISTORY := CONCAT(UPDATE_HISTORY, '-> OLD IMAGE_ALT_TAG: ', COALESCE(OLD.IMAGE_ALT_TAG, 'NULL'), 
                                     '; NEW IMAGE_ALT_TAG: ', COALESCE(NEW.IMAGE_ALT_TAG, 'NULL'), CHAR(13), CHAR(10));
    END IF;

    -- Handle HOLIDAY_TYPE with NULL check
    IF (COALESCE(NEW.HOLIDAY_TYPE, '') != COALESCE(OLD.HOLIDAY_TYPE, '')) THEN
        SET UPDATE_HISTORY := CONCAT(UPDATE_HISTORY, '-> OLD HOLIDAY_TYPE: ', COALESCE(OLD.HOLIDAY_TYPE, 'NULL'), 
                                     '; NEW HOLIDAY_TYPE: ', COALESCE(NEW.HOLIDAY_TYPE, 'NULL'), CHAR(13), CHAR(10));
    END IF;

    -- Handle INTERNAL_OFFER with NULL check
    IF (COALESCE(NEW.INTERNAL_OFFER, '') != COALESCE(OLD.INTERNAL_OFFER, '')) THEN
        SET UPDATE_HISTORY := CONCAT(UPDATE_HISTORY, '-> OLD INTERNAL_OFFER: ', COALESCE(OLD.INTERNAL_OFFER, 'NULL'), 
                                     '; NEW INTERNAL_OFFER: ', COALESCE(NEW.INTERNAL_OFFER, 'NULL'), CHAR(13), CHAR(10));
    END IF;

    -- Handle MODULE with NULL check
    IF (COALESCE(NEW.MODULE, '') != COALESCE(OLD.MODULE, '')) THEN
        SET UPDATE_HISTORY := CONCAT(UPDATE_HISTORY, '-> OLD MODULE: ', COALESCE(OLD.MODULE, 'NULL'), 
                                     '; NEW MODULE: ', COALESCE(NEW.MODULE, 'NULL'), CHAR(13), CHAR(10));
    END IF;

    -- Handle PROMO_CODE_NAME with NULL check
    IF (COALESCE(NEW.PROMO_CODE_NAME, '') != COALESCE(OLD.PROMO_CODE_NAME, '')) THEN
        SET UPDATE_HISTORY := CONCAT(UPDATE_HISTORY, '-> OLD PROMO_CODE_NAME: ', COALESCE(OLD.PROMO_CODE_NAME, 'NULL'), 
                                     '; NEW PROMO_CODE_NAME: ', COALESCE(NEW.PROMO_CODE_NAME, 'NULL'), CHAR(13), CHAR(10));
    END IF;

    -- Handle DESTINATION_NAME with NULL check
    IF (COALESCE(NEW.DESTINATION_NAME, '') != COALESCE(OLD.DESTINATION_NAME, '')) THEN
        SET UPDATE_HISTORY := CONCAT(UPDATE_HISTORY, '-> OLD DESTINATION_NAME: ', COALESCE(OLD.DESTINATION_NAME, 'NULL'), 
                                     '; NEW DESTINATION_NAME: ', COALESCE(NEW.DESTINATION_NAME, 'NULL'), CHAR(13), CHAR(10));
    END IF;

    -- Handle REMARK with NULL check
    IF (COALESCE(NEW.REMARK, '') != COALESCE(OLD.REMARK, '')) THEN
        SET UPDATE_HISTORY := CONCAT(UPDATE_HISTORY, '-> OLD REMARK: ', COALESCE(OLD.REMARK, 'NULL'), 
                                     '; NEW REMARK: ', COALESCE(NEW.REMARK, 'NULL'), CHAR(13), CHAR(10));
    END IF;

    -- Handle OFFER_FROM_DATE with NULL check for dates
    IF (COALESCE(NEW.OFFER_FROM_DATE, '1900-01-01') != COALESCE(OLD.OFFER_FROM_DATE, '1900-01-01')) THEN
        SET UPDATE_HISTORY := CONCAT(UPDATE_HISTORY, '-> OLD OFFER_FROM_DATE: ', COALESCE(OLD.OFFER_FROM_DATE, 'NULL'), 
                                     '; NEW OFFER_FROM_DATE: ', COALESCE(NEW.OFFER_FROM_DATE, 'NULL'), CHAR(13), CHAR(10));
    END IF;

    -- Handle OFFER_TO_DATE with NULL check for dates
    IF (COALESCE(NEW.OFFER_TO_DATE, '1900-01-01') != COALESCE(OLD.OFFER_TO_DATE, '1900-01-01')) THEN
        SET UPDATE_HISTORY := CONCAT(UPDATE_HISTORY, '-> OLD OFFER_TO_DATE: ', COALESCE(OLD.OFFER_TO_DATE, 'NULL'), 
                                     '; NEW OFFER_TO_DATE: ', COALESCE(NEW.OFFER_TO_DATE, 'NULL'), CHAR(13), CHAR(10));
    END IF;

    -- Always insert audit record if there are any changes (even if UPDATE_HISTORY is empty)
    -- This ensures audit trail for any update operation
    IF (NEW.HOLIDAY_OFFER_NAME != OLD.HOLIDAY_OFFER_NAME OR 
        COALESCE(NEW.IS_ACTIVE, '') != COALESCE(OLD.IS_ACTIVE, '') OR
        COALESCE(NEW.IMAGE_NAME, '') != COALESCE(OLD.IMAGE_NAME, '') OR
        COALESCE(NEW.IMAGE_ALT_TAG, '') != COALESCE(OLD.IMAGE_ALT_TAG, '') OR
        COALESCE(NEW.HOLIDAY_TYPE, '') != COALESCE(OLD.HOLIDAY_TYPE, '') OR
        COALESCE(NEW.INTERNAL_OFFER, '') != COALESCE(OLD.INTERNAL_OFFER, '') OR
        COALESCE(NEW.MODULE, '') != COALESCE(OLD.MODULE, '') OR
        COALESCE(NEW.PROMO_CODE_NAME, '') != COALESCE(OLD.PROMO_CODE_NAME, '') OR
        COALESCE(NEW.DESTINATION_NAME, '') != COALESCE(OLD.DESTINATION_NAME, '') OR
        COALESCE(NEW.REMARK, '') != COALESCE(OLD.REMARK, '') OR
        COALESCE(NEW.OFFER_FROM_DATE, '1900-01-01') != COALESCE(OLD.OFFER_FROM_DATE, '1900-01-01') OR
        COALESCE(NEW.OFFER_TO_DATE, '1900-01-01') != COALESCE(OLD.OFFER_TO_DATE, '1900-01-01')) THEN
        
        INSERT INTO TCIL_MST_HOLIDAY_OFFERS_AUDIT (
            HOLIDAY_OFFER_ID,
            UPDATE_DATE,
            UPDATED_BY,
            IP,
            HISTORY
        ) VALUES (
            NEW.HOLIDAY_OFFER_ID,
            NOW(),
            NEW.UPDATED_BY,
            NEW.IP,
            CASE 
                WHEN LENGTH(UPDATE_HISTORY) > 0 THEN CONCAT(UPDATE_HISTORY, 'Updated')
                ELSE 'Record Updated'
            END
        );
    END IF;
END$$

DELIMITER ;